baseURL = 'http://example.org/'
languageCode = 'en-us'
title = "tk's showcase"
theme = "PaperMod"
[markup.goldmark.renderer]
  unsafe = true
# [params]
#   mathjax = true
[params.assets]
     disableHLJS = true
     favicon = "/favicon.ico"
     favicon16x16 = "/favicon-16x16.png"
     favicon32x32 = "/favicon-32x32.png"
     apple_touch_icon = "/apple-touch-icon.png"
     safari_pinned_tab = "/safari-pinned-tab.svg"
[params]
    hideFooter = true