
** 棋牌

*** 德州扑克
*** 麻将
***** ref
[[https://www.bilibili.com/video/BV1eu411R7XH/?spm_id_from=333.337.search-card.all.click&vd_source=41e24bb77945169d39b2f0825457551e][四川麻将规则介绍零基础，四川麻将新手入门知识视频！入门初学者 🔊]] 这个视频虽然内容不算全面, 但是让我理解了一些基本概念. 非常推荐.
百度网盘中存的 麻将规则.pdf([[http://www.mindmahjong.com/adobe/20141120CEJ.pdf][麻将竞赛规则（中英日）20150114合并附件4.indd]])是中日麻将比赛的, 解释术语还是清楚的.
[[https://www.jj.cn/news/320/20111024100100019326.shtml][四川麻将规则-常见问题-JJ帮助中心]] 介绍不同番数是有用的.

***** 从哪里开始拿牌, 掷骰子

108 张牌, 每个人拿 3 堆, 12 张牌.
庄家是掷骰子的人. 有 2 个骰子. 掷一次.
确定从哪一堆开始拿牌: 庄家掷骰子, 点数和, 逆时针数. 庄家是 1.
再取 min, 顺时针数, 比如如果是 4, 就跳过 4 堆(上下重叠的两张牌是一堆). 拿 3 次. 一次拿 2 堆.

接下来是跳牌. 跳牌是从拿的一方的顺时针下一方开始拿.
顺时针
庄家|对家|庄家|
 占位|上家|下家|

***** 上家, 下家, 对家
这是一个相对的概念. 上家是说比你先出牌的, 下家是比你先出牌的. 对家是坐你对面的人.
***** 行牌过程: 逆时针, 碰(2+1), 杠(3+1)

庄家 14 张, 其他每人 13 张.

条, 饼, 万.

幺鸡就是一条.
胡牌的时候只能有 2 种牌, 这叫做打缺.

抓一张出一张.

吃: 我有一筒和三筒, 现在别人拿一个二筒, 就是吃. 然后再出牌. 不用抓牌. 四川麻将没有吃.

碰: 有人出了一饼, 我有 2 个, 我就可以拿过来再出牌. 

杠: 有 3 张, 有 3 个一饼, 再抓一个一饼, 就再抓一张牌. 再出牌. 注意, 杠会导致多一张牌.
明杠: 就是之前已经吃了, 别人知道你杠的是什么.
暗杠: 别人不知道, 是背着的.

四川麻将没有吃, 只有碰和杠.

胡牌: 有一对, 不管是什么, 反正是一对.
然后其它的是 12 张牌, 4 个三张, 顺子(连在一起的)或者一样都可以(刻子).

如果有杠, 反正就是 3, 4

7 小对也可以.
***** 输赢关系
不仅胡牌会构成输赢关系. 打到最后, 没叫的人还要给有交的人钱.
***** 点炮
点炮, 中国麻将用语, 意思是打出了某一家需要胡的牌, 又称放铳. 麻将术语, 打麻将时打出的牌正好使别人和 (胡) 牌.

***** 自摸
拿牌后成和牌

***** 番数
基本胡: 拿别人牌胡
碰碰胡: 所有的 3 张牌都不是连子, 是同一种花色.
金钩钓: 所有的 3 张牌都是碰出来的, 都是明牌
清一色
七对: +2 番, 4 番


***** 术语
****** 查大叫
意思就是打到最后还是没有下叫.
